version: '2'

services:
  teamcity:
    build: ./teamcity
    stdin_open: true
    tty: true
    volumes:
      - ./data:/data/teamcity_server/datadir:rw
      - ./logs:/opt/teamcity/logs:rw
    ports:
      - "8111:8111"

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.3.0.1/24
